---
# tasks file for apache
- name: Install Apache
  yum:
     name: httpd
     state: present
- name: Template a file to /etc/file.conf
  template:
      src: apache.j2
      dest: /etc/httpd/conf/httpd.conf

# ansible-playbook apache1playbook.yml --extra-vars "ansible_sudo_pass=GSC@gslab"

